# Generated by Django 4.1.2 on 2022-10-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='type',
            new_name='type_old',
        ),
    ]
