# Generated by Django 4.1.2 on 2022-10-13 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_type_taskmodel_type_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='type_old',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_old', to='webapp.tasktype', verbose_name='Тип'),
        ),
    ]
